development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://vjdgkoxltozxiz:3e0f574fd658c97ddc20f9c245d7e985badc9739cb2bb13821f7e0fcf78a4dcc@ec2-174-129-41-23.compute-1.amazonaws.com:5432/d55kmcigqu3ukg
